# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36, unique=True)),
                ('pid', models.IntegerField(null=True)),
                ('controler', models.CharField(max_length=36)),
                ('action', models.CharField(max_length=36)),
                ('level', models.SmallIntegerField(choices=[(b'0', b'\xe4\xb8\x80\xe7\xba\xa7'), (b'1', b'\xe4\xba\x8c\xe7\xba\xa7'), (b'2', b'\xe4\xb8\x89\xe7\xba\xa7')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='RightApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_id', models.IntegerField()),
                ('right_id_service', models.CharField(max_length=255)),
                ('right_api_action', models.CharField(max_length=255)),
                ('right_api_path', models.CharField(max_length=255)),
                ('right_api_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('role_name', models.CharField(max_length=36, unique=True)),
                ('ids', models.CharField(max_length=512)),
                ('controler_action', models.TextField(blank=True, null=True)),
                ('role_desc', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36, unique=True)),
                ('password', models.CharField(max_length=36)),
                ('rid', models.IntegerField(null=True)),
                ('mobile', models.CharField(max_length=36)),
                ('email', models.CharField(max_length=36)),
                ('state', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
