# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=36)),
                ('time', models.IntegerField(null=True)),
                ('role_id', models.IntegerField(null=True)),
                ('mobile', models.CharField(max_length=36)),
                ('email', models.CharField(max_length=36)),
                ('state', models.IntegerField(null=True)),
            ],
        ),
    ]
