# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
