# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='rid',
        ),
    ]
