# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200405_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('pid', models.IntegerField(null=True)),
                ('controler', models.CharField(max_length=36)),
                ('action', models.CharField(max_length=36)),
                ('level', models.SmallIntegerField(choices=[(b'1', b'\xe4\xb8\x80\xe7\xba\xa7'), (b'2', b'\xe4\xba\x8c\xe7\xba\xa7'), (b'3', b'\xe4\xb8\x89\xe7\xba\xa7')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RightApi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('right_id', models.CharField(max_length=255)),
                ('right_id_service', models.CharField(max_length=255)),
                ('right_api_action', models.CharField(max_length=255)),
                ('right_api_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(null=True)),
                ('role_name', models.CharField(max_length=36)),
                ('ids', models.CharField(max_length=512)),
                ('controler_action', models.TextField(blank=True, null=True)),
                ('role_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
