# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200411_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightapi',
            name='right_api_action',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rightapi',
            name='right_id_service',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
