# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200411_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightapi',
            name='right_api_order',
            field=models.IntegerField(null=True),
        ),
    ]
