# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200406_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
