# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200406_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='create_time',
            field=models.DateTimeField(default=datetime.date(2020, 4, 6)),
        ),
        migrations.AddField(
            model_name='right',
            name='delete_time',
            field=models.DateTimeField(default=datetime.date(2020, 4, 6)),
        ),
        migrations.AddField(
            model_name='right',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=datetime.date(2020, 4, 6)),
        ),
        migrations.AddField(
            model_name='role',
            name='delete_time',
            field=models.DateTimeField(default=datetime.date(2020, 4, 6)),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.date(2020, 4, 6)),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.date(2020, 4, 6)),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rightapi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
