# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200411_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='rid',
        ),
    ]
