# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_role_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
    ]
