# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200406_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
    ]
