# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200411_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=36),
        ),
    ]
