# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200406_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='name',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
